export enum PermissionName {
  // Products (existing)
  ACCESS_PRODUCTS_PAGE = 'ACCESS_PRODUCTS_PAGE',
  VIEW_PRODUCT = 'VIEW_PRODUCT',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  // Suppliers (existing)
  ACCESS_SUPPLIERS_PAGE = 'ACCESS_SUPPLIERS_PAGE',
  VIEW_SUPPLIER = 'VIEW_SUPPLIER',
  CREATE_SUPPLIER = 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER = 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER = 'DELETE_SUPPLIER',

  // Manufacturers (existing)
  ACCESS_MANUFACTURERS_PAGE = 'ACCESS_MANUFACTURERS_PAGE',
  VIEW_MANUFACTURER = 'VIEW_MANUFACTURER',
  CREATE_MANUFACTURER = 'CREATE_MANUFACTURER',
  UPDATE_MANUFACTURER = 'UPDATE_MANUFACTURER',
  DELETE_MANUFACTURER = 'DELETE_MANUFACTURER',

  // Construction Sites (existing)
  ACCESS_CONSTRUCTION_SITES_PAGE = 'ACCESS_CONSTRUCTION_SITES_PAGE',
  VIEW_CONSTRUCTION_SITE = 'VIEW_CONSTRUCTION_SITE',
  CREATE_CONSTRUCTION_SITE = 'CREATE_CONSTRUCTION_SITE',
  UPDATE_CONSTRUCTION_SITE = 'UPDATE_CONSTRUCTION_SITE',
  DELETE_CONSTRUCTION_SITE = 'DELETE_CONSTRUCTION_SITE',

  // Families (existing)
  ACCESS_FAMILIES_PAGE = 'ACCESS_FAMILIES_PAGE',
  VIEW_FAMILY = 'VIEW_FAMILY',
  CREATE_FAMILY = 'CREATE_FAMILY',
  UPDATE_FAMILY = 'UPDATE_FAMILY',
  DELETE_FAMILY = 'DELETE_FAMILY',

  // Subfamilies (existing)
  ACCESS_SUBFAMILIES_PAGE = 'ACCESS_SUBFAMILIES_PAGE',
  VIEW_SUBFAMILY = 'VIEW_SUBFAMILY',
  CREATE_SUBFAMILY = 'CREATE_SUBFAMILY',
  UPDATE_SUBFAMILY = 'UPDATE_SUBFAMILY',
  DELETE_SUBFAMILY = 'DELETE_SUBFAMILY',

  // Categories (existing)
  ACCESS_CATEGORIES_PAGE = 'ACCESS_CATEGORIES_PAGE',
  VIEW_CATEGORY = 'VIEW_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  // ── NEW ENTRIES ──

  // Warehouses
  ACCESS_WAREHOUSES_PAGE = 'ACCESS_WAREHOUSES_PAGE',
  VIEW_WAREHOUSE = 'VIEW_WAREHOUSE',
  CREATE_WAREHOUSE = 'CREATE_WAREHOUSE',
  UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE',
  DELETE_WAREHOUSE = 'DELETE_WAREHOUSE',

  // Depots
  ACCESS_DEPOTS_PAGE = 'ACCESS_DEPOTS_PAGE',
  VIEW_DEPOT = 'VIEW_DEPOT',
  CREATE_DEPOT = 'CREATE_DEPOT',
  UPDATE_DEPOT = 'UPDATE_DEPOT',
  DELETE_DEPOT = 'DELETE_DEPOT',

  // Calendar (limited to view + create events)
  ACCESS_CALENDAR_PAGE = 'ACCESS_CALENDAR_PAGE',
  VIEW_CALENDAR = 'VIEW_CALENDAR',
  CREATE_CALENDAR_EVENT = 'CREATE_CALENDAR_EVENT',

  ACCESS_IMPORTS_PAGE = 'ACCESS_IMPORTS_PAGE',
  VIEW_IMPORT = 'VIEW_IMPORT',
  CREATE_IMPORT = 'CREATE_IMPORT',
  CONFIRM_IMPORT = 'CONFIRM_IMPORT',
  DENY_IMPORT = 'DENY_IMPORT',

  // Exports
  ACCESS_EXPORTS_PAGE = 'ACCESS_EXPORTS_PAGE',
  VIEW_EXPORT = 'VIEW_EXPORT',
  CREATE_EXPORT = 'CREATE_EXPORT',
  CONFIRM_EXPORT = 'CONFIRM_EXPORT',
  DENY_EXPORT = 'DENY_EXPORT',

  // Requests (no create)
  ACCESS_REQUESTS_PAGE = 'ACCESS_REQUESTS_PAGE',
  VIEW_REQUEST = 'VIEW_REQUEST',
  CONFIRM_REQUEST = 'CONFIRM_REQUEST',
  DENY_REQUEST = 'DENY_REQUEST',

  // Returns (no create)
  ACCESS_RETURNS_PAGE = 'ACCESS_RETURNS_PAGE',
  VIEW_RETURN = 'VIEW_RETURN',
  CONFIRM_RETURN = 'CONFIRM_RETURN',
  DENY_RETURN = 'DENY_RETURN',

  ACCESS_PENDING_ACCOUNTS_PAGE = 'ACCESS_PENDING_ACCOUNTS_PAGE',
  VIEW_PENDING_ACCOUNT = 'VIEW_PENDING_ACCOUNT',
  CONFIRM_PENDING_ACCOUNT = 'CONFIRM_PENDING_ACCOUNT',
  DELETE_PENDING_ACCOUNT = 'DELETE_PENDING_ACCOUNT',

  // Confirmed Accounts
  ACCESS_CONFIRMED_ACCOUNTS_PAGE = 'ACCESS_CONFIRMED_ACCOUNTS_PAGE',
  VIEW_CONFIRMED_ACCOUNT = 'VIEW_CONFIRMED_ACCOUNT',
  UPDATE_CONFIRMED_ACCOUNT = 'UPDATE_CONFIRMED_ACCOUNT',
  DELETE_CONFIRMED_ACCOUNT = 'DELETE_CONFIRMED_ACCOUNT',
}
